name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日00:00 UTC（JST 09:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # 自分のトークンを使う場合は secrets.SUMMARY_GITHUB_TOKEN に設定
          GITHUB_TOKEN: ${{ github.token }}
        with:
          USERNAME: yamadan96
          BRANCH_NAME: "main"
          UTC_OFFSET: 9
          EXCLUDE: ""
          AUTO_PUSH: true  # ← README更新をしないシンプル安定構成
